import React,{useEffect,useMemo,useState}from'react';
import{BrainCircuit,CheckCircle2,CircleAlert,Loader2,Trash2,TestTube2,Plus,RefreshCw,ShieldCheck,RotateCw}from'lucide-react';

type Account={id:number;name:string;provider:string;model:string;enabled:boolean;priority:number;authMode:string;secretConfigured:boolean;accountEmail?:string|null;lastError?:string|null;lastUsedAt?:string|null;totalCalls:number;freeOnly?:boolean;disabledUntil?:string|null};
type Model={id:string;name:string;family:string;status:'stable'|'preview'|'deprecated';kind:string;freeTier:boolean};
type Provider={id:string;label:string;model:string;baseUrl:string;models:string[]};

const GEMINI_BASE='https://generativelanguage.googleapis.com/v1beta';
const PROVIDERS:Provider[]=[
 {id:'GEMINI',label:'Google Gemini — Free Tier',model:'gemini-3.7-flash',baseUrl:GEMINI_BASE,models:[]},
 {id:'GROQ',label:'Groq — Free tier',model:'llama-3.1-8b-instant',baseUrl:'https://api.groq.com/openai/v1',models:['llama-3.1-8b-instant']},
 {id:'MISTRAL',label:'Mistral — Free',model:'mistral-small-latest',baseUrl:'https://api.mistral.ai/v1',models:['mistral-small-latest','ministral-3-8b-latest','ministral-3-14b-latest']},
 {id:'OPENROUTER',label:'OpenRouter — modèles :free',model:'meta-llama/llama-3.3-70b-instruct:free',baseUrl:'https://openrouter.ai/api/v1',models:['meta-llama/llama-3.3-70b-instruct:free','google/gemma-3-27b-it:free','qwen/qwen3-32b:free']}
];

export const AIGatewayAdmin:React.FC=()=>{
 const[a,setA]=useState<Account[]>([]),[models,setModels]=useState<Model[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[testing,setTesting]=useState<number|null>(null),[adding,setAdding]=useState(false),[showAll,setShowAll]=useState(false);
 const[form,setForm]=useState({provider:'GEMINI',name:'',model:'gemini-3.7-flash',baseUrl:GEMINI_BASE,secret:'',priority:10,accountEmail:''});
 const selected=PROVIDERS.find(x=>x.id===form.provider)||PROVIDERS[0];
 const geminiModels=useMemo(()=>models.filter(m=>m.status!=='deprecated'&&(showAll||m.freeTier)),[models,showAll]);
 const load=async()=>{setLoading(true);try{const[r1,r2]=await Promise.all([fetch('/api/admin/ai/gateway/providers',{credentials:'include'}),fetch('/api/admin/ai/gateway/catalog',{credentials:'include'})]);const d1=await r1.json(),d2=await r2.json();if(!r1.ok)throw new Error(d1.error||'Chargement impossible');setA(d1.providers||[]);if(r2.ok)setModels(d2.gemini||[]);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const changeProvider=(provider:string)=>{const p=PROVIDERS.find(x=>x.id===provider)||PROVIDERS[0];const first=provider==='GEMINI'?(models.find(m=>m.status!=='deprecated'&&m.freeTier)?.id||'gemini-3.7-flash'):p.model;setForm(v=>({...v,provider,name:v.name||p.label,model:first,baseUrl:p.baseUrl}))};
 const add=async(e:React.FormEvent)=>{e.preventDefault();if(!form.name.trim()||!form.secret.trim())return;setAdding(true);setError('');try{const r=await fetch('/api/admin/ai/gateway/providers',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Enregistrement impossible');setForm(v=>({...v,name:'',secret:'',accountEmail:''}));await load()}catch(e:any){setError(e.message)}finally{setAdding(false)}};
 const test=async(id:number)=>{setTesting(id);setError('');try{const r=await fetch('/api/admin/ai/gateway/test',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Test échoué');alert(`✓ ${d.provider} · ${d.account} · ${d.model}\n${d.reply}`);await load()}catch(e:any){setError(e.message);await load()}finally{setTesting(null)}};
 const remove=async(id:number)=>{if(!confirm('Supprimer cette connexion IA ?'))return;const r=await fetch(`/api/admin/ai/gateway/providers/${id}`,{method:'DELETE',credentials:'include'});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||'Suppression impossible');return}load()};
 return <div className="space-y-6">
  <div className="rounded-3xl bg-slate-900 text-white p-6"><div className="flex items-start gap-4"><div className="p-3 rounded-2xl bg-indigo-500/20 text-indigo-300"><BrainCircuit className="w-6 h-6"/></div><div><h2 className="text-lg font-bold">AI Gateway — Gemini Free Multi-Account</h2><p className="text-xs text-slate-300 mt-1">Ajoutez autant de projets/comptes Gemini Free que nécessaire. Les credentials sont chiffrées côté serveur et le routeur bascule automatiquement en cas de 429/404.</p></div></div><div className="mt-5 grid md:grid-cols-4 gap-3 text-xs">{['Gemini 3.7 Flash','Gemini 3.5 Flash-Lite','Pool multi-comptes','Fallback 429 / 404'].map(x=><div key={x} className="rounded-2xl bg-white/5 p-4"><CheckCircle2 className="w-4 h-4 mb-2 text-emerald-300"/><b>{x}</b></div>)}</div></div>
  {error&&<div className="rounded-2xl bg-red-50 border border-red-200 text-red-800 p-3 text-xs flex gap-2"><CircleAlert className="w-4 h-4"/>{error}</div>}
  <div className="bg-white rounded-3xl border border-slate-200 p-6"><div className="flex gap-3 items-center"><ShieldCheck className="w-5 h-5 text-emerald-600"/><div><h3 className="font-bold">Comptes indépendants</h3><p className="text-xs text-slate-500 mt-1">Les quotas Gemini sont appliqués par projet Google, pas par clé API. Pour obtenir plusieurs quotas indépendants, ajoutez des comptes/projets distincts.</p></div></div></div>
  <form onSubmit={add} className="bg-white rounded-3xl border border-slate-200 p-6 space-y-4"><div className="flex items-center gap-2"><Plus className="w-4 h-4 text-indigo-600"/><h3 className="font-bold">Ajouter un compte Gemini / provider gratuit</h3></div><div className="grid md:grid-cols-2 gap-3">
   <label className="text-xs font-semibold">Provider<select value={form.provider} onChange={e=>changeProvider(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 font-normal">{PROVIDERS.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>
   <label className="text-xs font-semibold">Nom du compte<input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} className="mt-1 w-full rounded-xl border p-2.5 font-normal" placeholder="Gemini Free 1"/></label>
   <label className="text-xs font-semibold">Modèle<select value={form.model} onChange={e=>setForm(v=>({...v,model:e.target.value}))} className="mt-1 w-full rounded-xl border p-2.5 font-normal">{(form.provider==='GEMINI'?geminiModels:PROVIDERS.find(p=>p.id===form.provider)?.models||[]).map(m=><option key={typeof m==='string'?m:m.id} value={typeof m==='string'?m:m.id}>{typeof m==='string'?m:`${m.name} · ${m.id}`}</option>)}</select></label>
   <label className="text-xs font-semibold">Priorité<input type="number" value={form.priority} onChange={e=>setForm(v=>({...v,priority:Number(e.target.value)}))} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label>
   <label className="text-xs font-semibold">Email / identifiant du compte (optionnel)<input value={form.accountEmail} onChange={e=>setForm(v=>({...v,accountEmail:e.target.value}))} className="mt-1 w-full rounded-xl border p-2.5 font-normal" placeholder="compte1@gmail.com"/></label>
   <label className="text-xs font-semibold">Credential / API Key<input type="password" value={form.secret} onChange={e=>setForm(v=>({...v,secret:e.target.value}))} className="mt-1 w-full rounded-xl border p-2.5 font-mono font-normal" placeholder="AIza... — chiffrée côté serveur"/></label>
  </div><div className="flex justify-between items-center"><span className="text-[11px] text-slate-500">Aucune clé n'est renvoyée au navigateur après sauvegarde.</span><button disabled={adding||!form.secret.trim()} className="px-4 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-bold disabled:opacity-50">{adding?'Enregistrement…':'Ajouter au pool'}</button></div></form>
  <div className="bg-white rounded-3xl border border-slate-200 overflow-hidden"><div className="p-6 border-b border-slate-100 flex items-center justify-between"><div><h3 className="font-bold">Comptes configurés</h3><p className="text-xs text-slate-500 mt-1">{a.length} connexion(s). À priorité égale, le routeur favorise le compte le moins récemment utilisé.</p></div><button onClick={load} className="p-2 rounded-xl bg-slate-100"><RefreshCw className="w-4 h-4"/></button></div>
   {loading?<div className="p-8 text-center text-xs text-slate-500"><Loader2 className="w-5 h-5 animate-spin mx-auto mb-2"/>Chargement…</div>:!a.length?<div className="p-8 text-center text-xs text-slate-500">Aucun provider gratuit configuré.</div>:<div className="divide-y divide-slate-100">{a.map(x=><div key={x.id} className="p-5 flex items-center justify-between gap-4"><div className="min-w-0"><div className="font-bold text-sm">{x.name}</div><div className="text-[11px] text-slate-500">{x.provider} · {x.model} · priorité {x.priority}{x.accountEmail?` · ${x.accountEmail}`:''}</div><div className={`text-[11px] mt-1 ${x.lastError?'text-red-600':'text-emerald-600'}`}>{x.enabled?'🟢 Actif':'🔴 Désactivé'} · Credential chiffrée{x.totalCalls?` · ${x.totalCalls} appels`:''}</div>{x.disabledUntil&&<div className="text-[11px] text-amber-700 mt-1">Refroidissement jusqu'au {new Date(x.disabledUntil).toLocaleString('fr-FR')}</div>}{x.lastError&&<div className="text-[11px] text-red-600 mt-1 truncate max-w-xl">Dernière erreur: {x.lastError}</div>}</div><div className="flex gap-2 shrink-0"><button onClick={()=>test(x.id)} disabled={testing===x.id||!x.enabled} className="px-3 py-2 rounded-xl bg-slate-100 text-xs font-bold inline-flex gap-1 items-center disabled:opacity-50">{testing===x.id?<Loader2 className="w-3.5 h-3.5 animate-spin"/>:<TestTube2 className="w-3.5 h-3.5"/>}Tester</button><button onClick={async()=>{try{const r=await fetch(`/api/admin/ai/gateway/providers/${x.id}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!x.enabled})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Modification impossible');await load()}catch(e:any){setError(e.message)}}} title={x.enabled?'Désactiver':'Activer'} className={`px-3 py-2 rounded-xl text-xs font-bold ${x.enabled?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}>{x.enabled?'Désactiver':'Activer'}</button><button onClick={()=>remove(x.id)} className="p-2 rounded-xl bg-red-50 text-red-600"><Trash2 className="w-4 h-4"/></button></div></div>)}</div>}
  </div>
  <div className="bg-white rounded-3xl border border-slate-200 overflow-hidden"><div className="p-6 border-b border-slate-100 flex items-center justify-between"><div><h3 className="font-bold">Catalogue Gemini complet</h3><p className="text-xs text-slate-500 mt-1">Modèles actuels, preview et modèles arrêtés. Les modèles non gratuits sont affichés à titre informatif mais ne peuvent pas être ajoutés en mode FREE ONLY.</p></div><button onClick={()=>setShowAll(v=>!v)} className="px-3 py-2 rounded-xl bg-slate-100 text-xs font-bold">{showAll?'Afficher Free Tier':'Afficher tout'}</button></div><div className="divide-y divide-slate-100">{(showAll?models:models.filter(m=>m.status!=='deprecated')).map(m=><div key={m.id} className="p-4 flex items-center justify-between gap-4"><div><div className="text-sm font-semibold">{m.name}</div><div className="text-[11px] text-slate-500 font-mono">{m.id}</div></div><div className="flex gap-2 text-[10px] font-bold"><span className="rounded-full bg-slate-100 px-2 py-1">{m.family}</span><span className={`rounded-full px-2 py-1 ${m.status==='stable'?'bg-emerald-50 text-emerald-700':m.status==='preview'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{m.status}</span>{m.freeTier&&<span className="rounded-full bg-blue-50 text-blue-700 px-2 py-1">FREE</span>}</div></div>)}</div></div>
 </div>
};
