# Generated by GitHub Actions. Do not commit the generated inventory.
[web]
${vm_public_ip} ansible_user=${admin_username} ansible_ssh_private_key_file=${ssh_key_path} ansible_python_interpreter=/usr/bin/python3

[web:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
